plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    implementation 'com.electronwill.night-config:toml:3.8.0'

    // EMI
    modImplementation "dev.emi:emi-fabric:${emi_version}:api"

    // Cloth Config
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}"
    modImplementation "com.terraformersmc:modmenu:${mod_menu_version}"

    // Item Descriptions
    modRuntimeOnly "folk.sisby:kaleido-config:${kaleido_config_version}"
    modImplementation "maven.modrinth:item-descriptions:${item_descriptions_version}-fabric"

    // Immersive Overlays
    modRuntimeOnly "maven.modrinth:immersive-overlays:${immersive_overlays_version}-fabric"

    // Spyglass Improvements
    modRuntimeOnly "maven.modrinth:spyglass-improvements:${spyglass_improvements_version}+fabric"

    // ETF & EMF
    modCompileOnly "maven.modrinth:entitytexturefeatures:${etf_version}-fabric-1.21"
    modCompileOnly "maven.modrinth:entity-model-features:${emf_version}-fabric-1.21"

    // Reliable Remover
    modCompileOnly "maven.modrinth:reliable-remover:${reliable_remover_version}-fabric-1.21.1"

    // Exposure
    modImplementation "maven.modrinth:exposure:${exposure_fabric_version}"
    modImplementation "maven.modrinth:forge-config-api-port:${fcapi_version}-Fabric"

    // No Man's Land
    compileOnly "maven.modrinth:no-mans-land:${no_mans_land_version}"

    // Cobblemon
    modCompileOnly "com.cobblemon:fabric:${cobblemon_version}"

    // Serene Seasons
    modCompileOnly "maven.modrinth:serene-seasons:${serene_seasons_fabric_version}"

    // Fabric Seasons
    modCompileOnly "maven.modrinth:fabric-seasons:${fabric_seasons_version}"
    modRuntimeOnly "maven.modrinth:fabric-seasons:${fabric_seasons_version}"

    // Scholar
    modImplementation "maven.modrinth:scholar:MpMbLKGR"

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file = tasks.named("remapJar").flatMap { it.archiveFile }
}