plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly "maven.modrinth:no-mans-land:${no_mans_land_version}"
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "dev.emi:emi-xplat-mojmap:${emi_version}:api"
    
    compileOnly "maven.modrinth:entitytexturefeatures:${etf_version}-neoforge-1.21"
    compileOnly "maven.modrinth:entity-model-features:${emf_version}-neoforge-1.21"
    compileOnly "maven.modrinth:reliable-remover:${reliable_remover_version}-neoforge-1.21.1"
    compileOnly "maven.modrinth:exposure:${exposure_neoforge_version}"
    compileOnly "maven.modrinth:mixed-litter:${mixed_litter_version}"
    compileOnly "com.cobblemon:neoforge:${cobblemon_version}"
    compileOnly "maven.modrinth:serene-seasons:${serene_seasons_neoforge_version}"
    compileOnly "maven.modrinth:scholar:t5aJhKGV"
    compileOnly "maven.modrinth:item-descriptions:${item_descriptions_version}-neoforge"

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.6'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}