plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    // Item Descriptions
    implementation "maven.modrinth:item-descriptions:${item_descriptions_version}-neoforge"

    // EMI
    implementation "dev.emi:emi-neoforge:${emi_version}:api"

    // Cloth Config
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"

    // Immersive Overlays
    implementation "maven.modrinth:immersive-overlays:${immersive_overlays_version}-neoforge"

    // Spyglass Improvements
    //runtimeOnly "maven.modrinth:spyglass-improvements:${spyglass_improvements_version}+neoforge"

    // ETF & EMF
    compileOnly "maven.modrinth:entitytexturefeatures:${etf_version}-neoforge-1.21"
    compileOnly "maven.modrinth:entity-model-features:${emf_version}-neoforge-1.21"

    // Reliable Remover
    compileOnly "maven.modrinth:reliable-remover:${reliable_remover_version}-neoforge-1.21.1"

    // Exposure
    compileOnly "maven.modrinth:exposure:${exposure_neoforge_version}"
    //runtimeOnly "maven.modrinth:exposure:${exposure_neoforge_version}"

    // Mixed Litter
    compileOnly "maven.modrinth:mixed-litter:${mixed_litter_version}"

    // No Man's Land
    implementation "maven.modrinth:no-mans-land:${no_mans_land_version}"
    runtimeOnly "maven.modrinth:biolith:xaeaSA9Q"

    // Primal
    compileOnly "maven.modrinth:mod-primal:${primal_version}"

    // Cobblemon
    compileOnly "com.cobblemon:neoforge:${cobblemon_version}"

    // KubeJS
    compileOnly "maven.modrinth:kubejs:${kubejs_version}"

    // Serene Seasons
    compileOnly "maven.modrinth:serene-seasons:${serene_seasons_neoforge_version}"
    //runtimeOnly "maven.modrinth:serene-seasons:${serene_seasons_neoforge_version}"
    //runtimeOnly "maven.modrinth:glitchcore:8wmCpbQ2"

    // Ecliptic Seasons
    //runtimeOnly "maven.modrinth:ecliptic-seasons:${ecliptic_seasons_version}"

    // Scholar
    compileOnly "maven.modrinth:scholar:t5aJhKGV"
    runtimeOnly "maven.modrinth:scholar:t5aJhKGV"
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}
